### ISSUE TITLE
評価方法の決定

### ISSUE THREAD

**Issue by yuya-inagaki** [yuya-inagaki/web-saliency-map#4]
[Saliency Metrics](https://github.com/yuya-inagaki/saliency_metrics)を使用して判断

**ToDo**

- [x] 出力した顕著性マップと同じ状態のGround Truth Saliency Mapを出力する
- [x] Ground truth saliency mapを使用して顕著領域マップの生成を行う
- [x] Saliency Metricsを使用してGround Truthと比較評価を行う

**Comment by yuya-inagaki** [comment]
**評価モデル**

| モデル名 | 説明 | 参考URL |
| --- | --- | --- |
| Element level Ground Truth | 要素レベルでのGround Truth | https://github.com/yuya-inagaki/web-saliency-map |
| Itti & Koch | Itti & KochのbiasなしのSaliency map | none |
| SalNet | Deep Convolutional Networks for Saliency Prediction | https://algorithmia.com/algorithms/deeplearning/SalNet |
| ML-NET | A Deep Multi-Level Network for Saliency Prediction | https://github.com/marcellacornia/mlnet |

**評価指標**

| 略称 | 指標名 | 説明 |
| --- | --- | --- |
| AUC↑ | auc judd | AUCはArea under the curveの略、曲線下の面積を意味する |
| CC↑ | cc score | 推定された顕著性マップとグラウンドトゥルースマップの間の線形相関を測定 |
| KL↓ | kldiv score | ターゲットと予測された分布の間の距離をキャプチャする距離の尺度 |

**Comment by yuya-inagaki** [comment]
**SalNet**

以下のアドレスに画像と保存場所をjsonでPOST
https://api.algorithmia.com/v1/algo/deeplearning/SalNet/0.2.2?timeout=300
``` 
{
    "image": "https://raw.githubusercontent.com/yuya-inagaki/research/master/experiment/dataset/screenshot/C01-01-PASMO.png",
    "location": "data://yuya_inagaki/SalNet/C01-01.png"
}
```
以下のアドレスに出力される
https://algorithmia.com/data/hosted/yuya_inagaki/SalNet

**Comment by yuya-inagaki** [comment]
**ML-NET**

`/Users/yuya-inagaki/Documents/workspace/python/mlnet` にて実行
画像ディレクトリ `images` に画像を保存
```
python main.py test images/
```

**Comment by yuya-inagaki** [comment]
## 結果例
**C01-01**

| model | AUC↑ | CC↑ | KL↓ |
| --- | --- | --- | --- |
| original | 0.731 | 0.920 | 0.019 |
| salnet | 0.540 | 0.743 | 0.142 |
| mlnet | 0.629 | 0.825 | 0.047 |
